In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Pakistan Largest Ecommerce Dataset.csv")

C:\Users\SAAD\AppData\Local\Temp\ipykernel_3748\2481702470.py:1: DtypeWarning: Columns (0: status, 1: created_at, 2: sku, 3: increment_id, 4: category_name_1, 5: sales_commission_code, 6: payment_method, 7: Working Date, 8: BI Status, 9:  MV , 10: Customer Since, 11: M-Y, 12: FY) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Pakistan Largest Ecommerce Dataset.csv")

In [3]:
df.shape

(1048575, 26)

In [4]:
df.head()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.0,complete,7/1/2016,kreations_YI 06-L,1950.0,1.0,1950.0,100147443,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,1.0,NaN,NaN,NaN,NaN,NaN
1,211133.0,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.0,1.0,240.0,100147444,Beauty & Grooming,\N,...,7.0,2016-7,7-2016,FY17,2.0,NaN,NaN,NaN,NaN,NaN
2,211134.0,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.0,1.0,2450.0,100147445,Women's Fashion,\N,...,7.0,2016-7,7-2016,FY17,3.0,NaN,NaN,NaN,NaN,NaN
3,211135.0,complete,7/1/2016,kcc_krone deal,360.0,1.0,60.0,100147446,Beauty & Grooming,R-FSD-52352,...,7.0,2016-7,7-2016,FY17,4.0,NaN,NaN,NaN,NaN,NaN
4,211136.0,order_refunded,7/1/2016,BK7010400AG,555.0,2.0,1110.0,100147447,Soghaat,\N,...,7.0,2016-7,7-2016,FY17,5.0,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  float64
 1   status                 584509 non-null  str
 2   created_at             584524 non-null  str
 3   sku                    584504 non-null  str
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  float64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  str
 9   sales_commission_code  447346 non-null  str
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  str
 12  Working Date           584524 non-null  str
 13  BI Status              584524 non-null  str
 14   MV                    584524 non-null  str
 15  Year                   584524 non-null  float64
 16  Month                  584524 non-null  float64
 17  Customer Since         584513 non-null  str
 18  M-Y                    584524 non-null  str
 19  FY                     584524 non-null  str
 20  Customer ID            584513 non-null  float64
 21  Unnamed: 21            0 non-null       float64
 22  Unnamed: 22            0 non-null       float64
 23  Unnamed: 23            0 non-null       float64
 24  Unnamed: 24            0 non-null       float64
 25  Unnamed: 25            0 non-null       float64
dtypes: float64(13), object(1), str(12)
memory usage: 263.2+ MB

In [6]:
df.columns

Index(['item_id', 'status', 'created_at', 'sku', 'price', 'qty_ordered',
       'grand_total', 'increment_id', 'category_name_1',
       'sales_commission_code', 'discount_amount', 'payment_method',
       'Working Date', 'BI Status', ' MV ', 'Year', 'Month', 'Customer Since',
       'M-Y', 'FY', 'Customer ID', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23',
       'Unnamed: 24', 'Unnamed: 25'],
      dtype='str')

In [7]:
df.describe

<bound method NDFrame.describe of           item_id          status created_at  \
0        211131.0        complete   7/1/2016
1        211133.0        canceled   7/1/2016
2        211134.0        canceled   7/1/2016
3        211135.0        complete   7/1/2016
4        211136.0  order_refunded   7/1/2016
...           ...             ...        ...
1048570       NaN             NaN        NaN
1048571       NaN             NaN        NaN
1048572       NaN             NaN        NaN
1048573       NaN             NaN        NaN
1048574       NaN             NaN        NaN

                                                       sku   price  \
0                                        kreations_YI 06-L  1950.0
1        kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...   240.0
2                                       Ego_UP0017-999-MR0  2450.0
3                                           kcc_krone deal   360.0
4                                              BK7010400AG   555.0
...                                                    ...     ...
1048570                                                NaN     NaN
1048571                                                NaN     NaN
1048572                                                NaN     NaN
1048573                                                NaN     NaN
1048574                                                NaN     NaN

         qty_ordered  grand_total increment_id    category_name_1  \
0                1.0       1950.0    100147443    Women's Fashion
1                1.0        240.0    100147444  Beauty & Grooming
2                1.0       2450.0    100147445    Women's Fashion
3                1.0         60.0    100147446  Beauty & Grooming
4                2.0       1110.0    100147447            Soghaat
...              ...          ...          ...                ...
1048570          NaN          NaN          NaN                NaN
1048571          NaN          NaN          NaN                NaN
1048572          NaN          NaN          NaN                NaN
1048573          NaN          NaN          NaN                NaN
1048574          NaN          NaN          NaN                NaN

        sales_commission_code  ...  Month Customer Since     M-Y    FY  \
0                          \N  ...    7.0         2016-7  7-2016  FY17
1                          \N  ...    7.0         2016-7  7-2016  FY17
2                          \N  ...    7.0         2016-7  7-2016  FY17
3                 R-FSD-52352  ...    7.0         2016-7  7-2016  FY17
4                          \N  ...    7.0         2016-7  7-2016  FY17
...                       ...  ...    ...            ...     ...   ...
1048570                   NaN  ...    NaN            NaN     NaN   NaN
1048571                   NaN  ...    NaN            NaN     NaN   NaN
1048572                   NaN  ...    NaN            NaN     NaN   NaN
1048573                   NaN  ...    NaN            NaN     NaN   NaN
1048574                   NaN  ...    NaN            NaN     NaN   NaN

        Customer ID  Unnamed: 21  Unnamed: 22 Unnamed: 23 Unnamed: 24  \
0               1.0          NaN          NaN         NaN         NaN
1               2.0          NaN          NaN         NaN         NaN
2               3.0          NaN          NaN         NaN         NaN
3               4.0          NaN          NaN         NaN         NaN
4               5.0          NaN          NaN         NaN         NaN
...             ...          ...          ...         ...         ...
1048570         NaN          NaN          NaN         NaN         NaN
1048571         NaN          NaN          NaN         NaN         NaN
1048572         NaN          NaN          NaN         NaN         NaN
1048573         NaN          NaN          NaN         NaN         NaN
1048574         NaN          NaN          NaN         NaN         NaN

        Unnamed: 25
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
...             ...
1048570         NaN
1048571         NaN
1048572         NaN
1048573         NaN
1048574         NaN

[1048575 rows x 26 columns]>

In [8]:
#find which column has only null values in the dataset
df.isnull().all()

item_id                  False
status                   False
created_at               False
sku                      False
price                    False
qty_ordered              False
grand_total              False
increment_id             False
category_name_1          False
sales_commission_code    False
discount_amount          False
payment_method           False
Working Date             False
BI Status                False
 MV                      False
Year                     False
Month                    False
Customer Since           False
M-Y                      False
FY                       False
Customer ID              False
Unnamed: 21               True
Unnamed: 22               True
Unnamed: 23               True
Unnamed: 24               True
Unnamed: 25               True
dtype: bool

In [9]:
df.isna().sum()

item_id                   464051
status                    464066
created_at                464051
sku                       464071
price                     464051
qty_ordered               464051
grand_total               464051
increment_id              464051
category_name_1           464215
sales_commission_code     601229
discount_amount           464051
payment_method            464051
Working Date              464051
BI Status                 464051
 MV                       464051
Year                      464051
Month                     464051
Customer Since            464062
M-Y                       464051
FY                        464051
Customer ID               464062
Unnamed: 21              1048575
Unnamed: 22              1048575
Unnamed: 23              1048575
Unnamed: 24              1048575
Unnamed: 25              1048575
dtype: int64

In [10]:
# now from the reamining , how many rows are completetly empty 
print(df.isna().all(axis=1).sum())

464051

In [15]:
print(df.dtypes)
df.head(10).loc[:, df.columns[12:20]]

item_id                  float64
status                       str
created_at                   str
sku                          str
price                    float64
qty_ordered              float64
grand_total              float64
increment_id              object
category_name_1              str
sales_commission_code        str
discount_amount          float64
payment_method               str
Working Date                 str
BI Status                    str
 MV                          str
Year                     float64
Month                    float64
Customer Since               str
M-Y                          str
FY                           str
Customer ID              float64
Unnamed: 21              float64
Unnamed: 22              float64
Unnamed: 23              float64
Unnamed: 24              float64
Unnamed: 25              float64
dtype: object

  Working Date BI Status       MV     Year  Month Customer Since     M-Y    FY
0     7/1/2016     #REF!    1,950   2016.0    7.0         2016-7  7-2016  FY17
1     7/1/2016     Gross      240   2016.0    7.0         2016-7  7-2016  FY17
2     7/1/2016     Gross    2,450   2016.0    7.0         2016-7  7-2016  FY17
3     7/1/2016       Net      360   2016.0    7.0         2016-7  7-2016  FY17
4     7/1/2016     Valid    1,110   2016.0    7.0         2016-7  7-2016  FY17
5     7/1/2016     Gross       80   2016.0    7.0         2016-7  7-2016  FY17
6     7/1/2016       Net      360   2016.0    7.0         2016-7  7-2016  FY17
7     7/1/2016       Net      170   2016.0    7.0         2016-7  7-2016  FY17
8     7/1/2016     Gross   96,499   2016.0    7.0         2016-7  7-2016  FY17
9     7/1/2016     Gross   96,499   2016.0    7.0         2016-7  7-2016  FY17

In [ ]:

(df["created_at"] != df["Working Date"]) (created_at != working Date),
    ["created_at", "Customer Since", "Year", "Month", "M-Y", "FY"]
].head(1)

       created_at Customer Since    Year  Month     M-Y    FY
254708   7/1/2017         2016-9  2017.0    7.0  7-2017  FY18

=>information acquired
1. unamed 21 to 25 are all null as null values == total number of rows, so we can just drop these ,refrence cell 9
2. we have 4646051 empty rows so we drop these rows as well,ref cell 10
3. change dtypes of cloumns : created_at:datetime , working date:datetime, customer since:datetime,